[package]
name = "clash-wsl2-mtu-fix"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
pnet = "0.28.0"
regex = "1.5.4"
