name: Go Build and Release

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.21'

      - name: Check out code
        uses: actions/checkout@v2

      - name: Get dependencies
        run: go get -v -t -d ./...

      - name: Build
        env:
          GOOS: linux
          GOARCH: amd64
        run: go build -v .

      - name: Test
        run: go test -v .

      - name: Archive production artifacts
        uses: actions/upload-artifact@v2
        with:
          name: clash-wsl2-mtu-fix
          path: ./main

  release:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Download artifacts
        uses: actions/download-artifact@v2
        with:
          name: clash-wsl2-mtu-fix

      - name: Release
        uses: softprops/action-gh-release@v1
        with:
          files: ./clash-wsl2-mtu-fix
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}